name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - uses: actions/setup-dotnet@v1
        if: matrix.os == 'ubuntu-latest'
        with:
            dotnet-version: '6.0.19'

      - name: Build
        run: ./gradlew -is --console plain nunit
